version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    container_name: docker-sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebookshop
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /data/mysql
  myapp:
    image: springdemo/myapp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app