package ebookshop.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ebookshop.dao.BookRepository;
import ebookshop.entity.Book;

@Service
public class BookService {
	@Autowired // get bean called bookRepository, which is auto-generated by Spring
	private BookRepository bookRepository;

	public Iterable<Book> getAllBooks() {
		return bookRepository.findAll();
	}

	public Optional<Book> getBook(int id) {
		return bookRepository.findById(id);
	}

	public Book createBook(Book book) {
		bookRepository.save(book);
		return book;
	}

	public Book updateBook(int id, Book bookDetails) {
		Book book = bookRepository.findById(id).orElseThrow(IllegalArgumentException::new);
		book.setTitle(bookDetails.getTitle());
		book.setAuthor(bookDetails.getAuthor());
		book.setPrice(bookDetails.getPrice());
		book.setQty(bookDetails.getQty());
		Book updatedBook = bookRepository.save(book);
		return updatedBook;
	}

	public boolean deleteBook(int id) {
		if (!bookRepository.existsById(id)) {
			return false;
		}

		bookRepository.deleteById(id);
		return true;
	}


	public Iterable<Book> getAvailableBooksByAuthor(String author) {
		return bookRepository.findByAuthorAndQtyGreaterThan(author, 0);
	}

	public void removeCopy(Book book) {
		book.setQty(book.getQty() - 1);
		bookRepository.save(book);
	}

}